import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Providers from './providers'
import { Montserrat } from 'next/font/google'

const montseratt = Montserrat({ subsets: ['latin-ext'] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${montseratt.className} antialiased`}
      >
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}
